# Generated by Django 5.1.2 on 2024-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('complete', 'Complete')], max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('high', 'High')], max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
